### ISSUE TITLE
/etc/init.d/nagira start doesn't start

### ISSUE THREAD

**Issue by fisches** [dmytro/nagira#30]
When I run the nagira-setup config:all everything works except when the services have to start.

And I check on the log file and I got this error:

/usr/local/rvm/gems/ruby-1.9.2-p320/gems/nagira-0.3.3/lib/app.rb:70:in `block in <class:Nagira>': undefined method `status_file' for #<Nagios::Config:0x00000015b5fcb0> (NoMethodError)
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/sinatra-1.3.6/lib/sinatra/base.rb:1356:in `configure'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/nagira-0.3.3/lib/app.rb:62:in `<class:Nagira>'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/nagira-0.3.3/lib/app.rb:53:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/nagira-0.3.3/bin/nagira:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/nagira:23:in `load'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/nagira:23:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/ruby_executable_hooks:15:in `<main>'

It strange because I try with different version of nagira and different version of ruby.
Maybe I do something wrong but I don't know.

For the moment nagira works only in test when I run it in the command line "nagira"

Thanks in advance.

**Comment by dmytro** [comment]
Same as #34
