### ISSUE TITLE
Do you know if this will work with OP5, or maybe it can be modified to work with it?

### ISSUE THREAD

**Issue by rjrobinson** [dmytro/nagira#35]
I know that OP5 and nagios are similar. Just checking if this has worked in the past.

**Comment by dmytro** [comment]
I don't have any experience with OP5, so can't say. Just looking at the OP5 web, since it is based on Nagios, there are chances Nagirqa can work with it.

**Comment by rjrobinson** [comment]
Thanks dmytro. Im currently working on testing this. and I'll send you an update when I come to some conclusions.
