### ISSUE TITLE
Unable to run the test configuration

### ISSUE THREAD

**Issue by ravanliyski** [dmytro/nagira#36]
Hello I am able to install the gem and run ''nagira', then when I try to setup test configuration i am facing this problem
Students-iMac:student1 student1$ nagira-setup config:test:install
(in /Users/student1/.rvm/gems/ruby-2.2.3/gems/nagira-0.5.0)
rake aborted!
NameError: uninitialized constant ActiveSupport::Concern
/Users/student1/.rvm/gems/ruby-2.2.3/gems/activemodel-4.2.5/lib/active_model/serializers/xml.rb:11:in `<module:Xml>'
/Users/student1/.rvm/gems/ruby-2.2.3/gems/activemodel-4.2.5/lib/active_model/serializers/xml.rb:10:in `<module:Serializers>'
/Users/student1/.rvm/gems/ruby-2.2.3/gems/activemodel-4.2.5/lib/active_model/serializers/xml.rb:8:in `<module:ActiveModel>'
/Users/student1/.rvm/gems/ruby-2.2.3/gems/activemodel-4.2.5/lib/active_model/serializers/xml.rb:7:in `<top (required)>'
/Users/student1/.rvm/gems/ruby-2.2.3/gems/nagira-0.5.0/lib/nagira.rb:2:in `<top (required)>'
/Users/student1/.rvm/gems/ruby-2.2.3/gems/nagira-0.5.0/Rakefile:2:in `require_relative'
/Users/student1/.rvm/gems/ruby-2.2.3/gems/nagira-0.5.0/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)

Any help will be appreciated.
Ravanliyski

**Comment by dmytro** [comment]
Your `Active*` gems are wrong version. Nagira requires 3.x versions.

Declared in `nagira.gemspec`.
```
s.add_dependency 'activemodel', '~> 3.2'
s.add_dependency 'activesupport', '~> 3.2'
```

Try to install Nagira as gem, you should have correct dependencies.

Also please note. I'm seeing that you're running Nagira on the Mac. You can only test Nagira in dev mode on Mac (i.e. with the provided test files only). I'm not even sure if Nagios is able to run on the MacOS.

**Comment by ravanliyski** [comment]
Many thanks, a lot of useful information
