### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by angelabad** [dmytro/nagira#39]
Hi, Its possible to use authentication to http requests to nagira?

I dont want all my nagios info to be public.

Thanks for your work.

Cheers,

**Comment by dmytro** [comment]
Nagira does not support authentication internally, but you could put it behind the Nginx or Apache. Using web server in front of Puma is good idea anyway.

**Comment by angelabad** [comment]
Hi, thanks for the response, I tried with nginx and it works well.

Cheers,
